import AnimatedShowcase from "@/components/AnimatedShowcase";
import AutoGeneratedSummaryShowcase from "@/components/AutoGeneratedSummaryShowcase";
import BallDropSpring from "@/components/BallDropSpring";
import ImageWheel from "@/components/ImageWheel";
import UseAnimate from "@/components/UseAnimate";

export default function Home() {
  return (
    <main className="grid h-screen place-content-center">
      <AutoGeneratedSummaryShowcase />
    </main>
  );
}
