import AccordionUsage from "@/components/AccordionUsage";
import AnimatedShowcase from "@/components/AnimatedShowcase";
import AutoGeneratedSummaryShowcase from "@/components/AutoGeneratedSummaryShowcase";
import BallDropSpring from "@/components/BallDropSpring";
import Button from "@/components/Button";
import ImageWheel from "@/components/ImageWheel";
import UseAnimate from "@/components/UseAnimate";

export default function Home() {
  return (
    <main className="grid h-screen place-content-center">
      {/*<AutoGeneratedSummaryShowcase />*/}
      {/*<AnimatedShowcase />*/}
      {/*<ImageWheel />*/}
      {/*<AccordionUsage />*/}
      <Button />
    </main>
  );
}
